export const SET_REMINDER_DATE = 'SET_REMINDER_DATE'
export const UNSET_REMINDER = 'UNSET_REMINDER'
export const INITIALIZE_REMINDER_LIST = 'INITIALIZE_REMINDER_LIST'
export const ADD_REMINDER_TO_LIST = 'ADD_REMINDER_TO_LIST'
