export const SET_REMINDED = "SET_REMINDED";
export const DELETE_REMINDED = "DELETE_REMINDED";
export const UNSET_REMINDER = "UNSET_REMINDER";
export const INITIALIZE_REMINDER_LIST = "INITIALIZE_REMINDER_LIST";
export const ADD_REMINDER_TO_LIST = "ADD_REMINDER_TO_LIST";
